import { CastMember, Episode, NavLink, NewsItem, PressAsset, PressContact, QuickFact, EnhancedCastMember, CastGroupInfo, GalleryImage } from './types';
import { buildImageUrl } from './lib/media';

export const NAV_LINKS: NavLink[] = [
  { label: 'Overview', href: '#overview' },
  { label: 'Cast', href: '#cast' },
  { label: 'Episodes', href: '#episodes' },
  { label: 'News', href: '/news' },
  { label: 'Gallery', href: '#gallery' },
  { label: 'Press Kit', href: '#presskit' },
  { label: 'Contact', href: '#contact' },
];

export const EPISODES: Episode[] = [
];

export const NEWS_ITEMS: NewsItem[] = [
  {
    id: 'n1',
    title: 'Casting Call: Winston Salem, NC',
    summary: 'The search for new faces continues! T.O.N.Y. is heading to North Carolina for a major casting expansion this Spring.',
    date: 'March 15, 2026',
    category: 'Casting',
    imageUrl: buildImageUrl('press', 'text/tony-press-03', 'card'),
  },
  {
    id: 'n2',
    title: 'New Episodes in Production',
    summary: 'The saga continues. Production has officially resumed for the next chapters of the Cortez family legacy.',
    date: 'March 12, 2026',
    category: 'Production',
    imageUrl: buildImageUrl('bts', 'tony-bts-01', 'card'),
  },
  {
    id: 'n3',
    title: 'Roku App & Website Launch',
    summary: 'Experience T.O.N.Y. like never before. Our official Roku channel and all-new web platform are now live and streaming.',
    date: 'March 10, 2026',
    category: 'Platform',
    imageUrl: buildImageUrl('press', 'magazine/tony-magazine-02', 'card'),
  },
];

export const SOCIAL_LINKS = {
  youtube: 'https://www.youtube.com/@TONYSeries',
  tiktok: 'https://www.tiktok.com/@tonyseries',
  instagram: 'https://www.instagram.com/tonyseries/',
  twitter: 'https://twitter.com/tonyseries',
  facebook: 'https://www.facebook.com/tonyseries',
  discord: 'https://discord.gg/tonyseries',
};

// Press Kit Data
export const QUICK_FACTS: QuickFact[] = [
  { label: 'Genre', value: 'Crime Drama' },
  { label: 'Creator', value: 'Michael Steven-Paul' },
  { label: 'Episodes', value: '10 per season' },
  { label: 'Runtime', value: '48-52 min' },
  { label: 'Network', value: 'Streaming' },
  { label: 'Premiere', value: 'Oct 2023' },
];

export const PRESS_CONTACTS: PressContact[] = [
  { name: 'Press Inquiries', role: 'Media Relations', email: 'press@tonyseries.com' },
  { name: 'Partnerships', role: 'Business Development', email: 'partners@tonyseries.com' },
];

export const PRESS_ASSETS: PressAsset[] = [
  // Photos
  {
    id: 'cast-headshots',
    title: 'Cast Headshots Pack',
    category: 'photo',
    description: 'High-resolution headshots of all main cast members',
    thumbnailUrl: buildImageUrl('cast', 'tony-cast-29', 'card'),
    downloadUrl: '/assets/press/TONY_cast_headshots.zip',
    fileSize: '45 MB',
    format: 'ZIP (JPEG)',
    resolution: '3000x4500 @ 300dpi',
  },
  {
    id: 'key-art',
    title: 'Key Art & Posters',
    category: 'photo',
    description: 'Official poster artwork and key promotional images',
    thumbnailUrl: buildImageUrl('press', 'posters/tony-poster-01', 'card'),
    downloadUrl: '/assets/press/TONY_key_art.zip',
    fileSize: '32 MB',
    format: 'ZIP (PNG/JPEG)',
    resolution: '4000x6000 @ 300dpi',
  },
  {
    id: 'bts-gallery',
    title: 'Behind-the-Scenes Gallery',
    category: 'photo',
    description: 'Exclusive on-set photos from production',
    thumbnailUrl: buildImageUrl('bts', 'tony-bts-01', 'card'),
    downloadUrl: '/assets/press/TONY_bts_gallery.zip',
    fileSize: '78 MB',
    format: 'ZIP (JPEG)',
    resolution: '4000x2667 @ 300dpi',
  },
  {
    id: 'episode-stills',
    title: 'Episode Stills',
    category: 'photo',
    description: 'Selected high-quality stills from Season 1 episodes',
    thumbnailUrl: buildImageUrl('gallery', 'tony-gallery-10', 'card'),
    downloadUrl: '/assets/press/TONY_episode_stills.zip',
    fileSize: '56 MB',
    format: 'ZIP (JPEG)',
    resolution: '3840x2160',
  },
  // Magazine Covers
  {
    id: 'magazine-cover-01',
    title: 'The Bronx Chronicle Cover',
    category: 'photo',
    description: 'Featured cover story on the creation of T.O.N.Y.',
    thumbnailUrl: buildImageUrl('press', 'magazine/tony-magazine-01', 'card'),
    downloadUrl: '#',
    fileSize: '8 MB',
    format: 'JPEG',
  },
  {
    id: 'magazine-cover-02',
    title: 'Street Impact Magazine',
    category: 'photo',
    description: 'Exclusive interview with Michael Steven-Paul',
    thumbnailUrl: buildImageUrl('press', 'magazine/tony-magazine-02', 'card'),
    downloadUrl: '#',
    fileSize: '12 MB',
    format: 'JPEG',
  },
  // Videos
  {
    id: 'official-trailer',
    title: 'Official Trailer',
    category: 'video',
    description: 'Season 1 official theatrical trailer',
    thumbnailUrl: buildImageUrl('gallery', 'tony-gallery-13', 'card'),
    downloadUrl: '/assets/press/TONY_S01_trailer_1080p.mp4',
    fileSize: '125 MB',
    format: 'MP4 (H.264)',
    resolution: '1920x1080',
    duration: '2:15',
  },
  // Logos
  {
    id: 'logo-primary',
    title: 'Primary Logo Pack',
    category: 'logo',
    description: 'Full logo in various formats (SVG, PNG, EPS)',
    thumbnailUrl: buildImageUrl('brand', 'tony-logo', 'card'),
    downloadUrl: '/assets/press/TONY_logo_primary.zip',
    fileSize: '2.5 MB',
    format: 'ZIP (SVG/PNG/EPS)',
  },
  // Documents
  {
    id: 'press-release',
    title: 'Press Release',
    category: 'document',
    description: 'Official press release for Season 1 premiere',
    thumbnailUrl: buildImageUrl('press', 'text/tony-press-04', 'card'),
    downloadUrl: '/assets/press/TONY_press_release.pdf',
    fileSize: '245 KB',
    format: 'PDF',
  },
  {
    id: 'fact-sheet',
    title: 'Series Fact Sheet',
    category: 'document',
    description: 'One-page overview with key facts and figures',
    thumbnailUrl: buildImageUrl('press', 'text/tony-press-05', 'card'),
    downloadUrl: '/assets/press/TONY_fact_sheet.pdf',
    fileSize: '180 KB',
    format: 'PDF',
  },
];

// BTS Gallery Images
export const GALLERY_IMAGES: GalleryImage[] = [
  {
    id: 'bts-set-01',
    title: 'On-Set Action',
    caption: 'Dynamic action capture from a key episode shoot.',
    imageUrl: buildImageUrl('bts', 'tony-bts-01', 'card'),
  },
  // Promotional & BTS Stills
  ...Array.from({ length: 24 }, (_, i) => ({
    id: `tony-gallery-${String(i + 1).padStart(2, '0')}`,
    title: `Bronx Scene Still ${i + 1}`,
    caption: 'Exclusive behind-the-scenes look at the production of T.O.N.Y.',
    imageUrl: buildImageUrl('gallery', `tony-gallery-${String(i + 1).padStart(2, '0')}`, 'card'),
  })).filter(img => img.id !== 'tony-gallery-11' && img.id !== 'tony-gallery-12'),
];

// Enhanced Cast System
export const CAST_GROUPS: CastGroupInfo[] = [
  { id: 'beaumont-family', label: 'The Beaumont Family' },
  { id: 'cortez-family', label: 'The Cortez Family' },
  { id: 'law-enforcement', label: 'Law Enforcement & Legal' },
  { id: 'street', label: 'Street & Supporting' },
  { id: 'community', label: 'Community & Faith' },
];

export const ENHANCED_CAST: EnhancedCastMember[] = [
  // === MAIN CAST ===
  {
    id: 'michael-cortez',
    characterName: 'MICHAEL "El Bastardo" CORTEZ',
    alias: 'El Bastardo',
    actorName: 'Michael Steven-Paul',
    group: 'cortez-family',
    order: 0,
    isFeatured: true,
    bio: 'The creator and lead of the series. Michael Cortez navigates the corrupt underbelly of NYC while trying to keep his family safe from the demons of his past.',
    imageUrl: buildImageUrl('cast', 'michael-steven-paul', 'cast'),
    traits: ['Mastermind', 'Ruthless', 'Family Man'],
  },
  {
    id: 'pheonix-beaumont',
    characterName: 'PHEONIX BEAUMONT (Miss B)',
    alias: 'Miss B',
    actorName: 'Michele White',
    group: 'beaumont-family',
    order: 2,
    isFeatured: false,
    imageUrl: buildImageUrl('cast', 'michele-white', 'cast'),
    traits: ['Queen Pin', 'Strategic', 'Fearless'],
    bio: 'The matriarch of the Beaumont empire. Miss B runs her operations with an iron fist and a velvet glove.',
  },
  {
    id: 'rina',
    characterName: 'RINA',
    actorName: 'Shana Bookman',
    group: 'street',
    order: 1,
    isFeatured: true,
    bio: 'Caught in the crossfire between families, Rina holds secrets that could reshape alliances or destroy them. Her survival depends on who she trusts—and who trusts her.',
    imageUrl: buildImageUrl('cast', 'shana-bookman', 'cast'),
    traits: ['Survivor', 'Secret Keeper', 'Unpredictable'],
  },
  {
    id: 'billy-black',
    characterName: 'BILLY BLACK',
    actorName: 'Britton L. Carter',
    group: 'street',
    order: 2,
    isFeatured: false,
    bio: 'A complex antagonist who rules the streets with a code of honor. His rivalry with Michael is personal, deep-rooted in their shared history in the Bronx.',
    imageUrl: buildImageUrl('cast', 'britton-carter', 'cast'),
    traits: ['Street King', 'Loyal', 'Dangerous'],
  },
  {
    id: 'enrique-cortez',
    characterName: 'ENRIQUE CORTEZ',
    actorName: 'Raymond Broadwater',
    group: 'cortez-family',
    order: 2,
    isFeatured: true,
    imageUrl: buildImageUrl('cast', 'raymond-broadwater', 'cast'),
    traits: ['Patriarch', 'Old School', 'Respected'],
    bio: 'The head of the Cortez family. His word is law, and his legacy is built on decades of power.',
  },

  // === THE BEAUMONT FAMILY ===
  {
    id: 'jenesis-beaumont',
    characterName: 'JENESIS BEAUMONT',
    actorName: 'Tatiana Honesty',
    group: 'beaumont-family',
    order: 1,
    imageUrl: buildImageUrl('cast', 'jenesis-beaumont', 'cast'),
  },
  {
    id: 'brandi-beaumont',
    characterName: 'BRANDI BEAUMONT',
    actorName: 'Bilae Harding',
    group: 'beaumont-family',
    order: 2,
    imageUrl: buildImageUrl('cast', 'brandi-beaumont', 'cast'),
  },
  {
    id: 'maxx-beaumont',
    characterName: 'MAXX BEAUMONT',
    actorName: 'Dwight Williams',
    group: 'beaumont-family',
    order: 3,
    imageUrl: buildImageUrl('cast', 'maxx-beaumont', 'cast'),
  },

  // === THE CORTEZ FAMILY ===
  {
    id: 'chelsea-alvarez',
    characterName: 'CHELSEA ALVAREZ',
    actorName: 'Kimani Sanders',
    group: 'cortez-family',
    order: 1,
    imageUrl: buildImageUrl('cast', 'chelsea-alvarez', 'cast'),
  },
  {
    id: 'ricardo-alvarez',
    characterName: 'RICARDO ALVAREZ "Big Chicken"',
    alias: 'Big Chicken',
    actorName: 'John Garcia',
    group: 'cortez-family',
    order: 2,
    imageUrl: buildImageUrl('cast', 'ricardo-alvarez', 'cast'),
  },
  {
    id: 'domingo',
    characterName: 'DOMINGO (Sonny)',
    alias: 'Sonny',
    actorName: 'Giodarni Vargas',
    group: 'cortez-family',
    order: 3,
    imageUrl: buildImageUrl('cast', 'domingo', 'cast'),
  },

  // === LAW ENFORCEMENT & LEGAL ===
  {
    id: 'captain-reigns',
    characterName: 'NYPD CAPTAIN REIGNS',
    actorName: 'Liana Battise',
    group: 'law-enforcement',
    order: 1,
    imageUrl: buildImageUrl('cast', 'captain-reigns', 'cast'),
  },
  {
    id: 'detective-chase',
    characterName: 'NYPD DETECTIVE CHASE',
    actorName: 'Gilly Delgado',
    group: 'law-enforcement',
    order: 2,
    imageUrl: buildImageUrl('cast', 'detective-chase', 'cast'),
  },
  {
    id: 'detective-barnes',
    characterName: 'NYPD DETECTIVE BARNES',
    actorName: 'Lezette Newland',
    group: 'law-enforcement',
    order: 1,
    isFeatured: true,
    imageUrl: buildImageUrl('cast', 'detective-barnes', 'cast'),
    bio: 'A sharp, no-nonsense detective on the front lines of the Bronx. Detective Barnes knows the streets as well as those who rule them.',
  },
  {
    id: 'detective-waters',
    characterName: 'NYPD DETECTIVE WATERS',
    actorName: 'Corrina Lynch',
    group: 'law-enforcement',
    order: 4,
    imageUrl: buildImageUrl('cast', 'detective-waters', 'cast'),
  },
  {
    id: 'detective-kazaan',
    characterName: 'NYPD DETECTIVE KAZAAN',
    actorName: 'Fallon Shaya',
    group: 'law-enforcement',
    order: 5,
    imageUrl: buildImageUrl('cast', 'detective-kazaan', 'cast'),
  },
  {
    id: 'levie-maxxi',
    characterName: 'NYPD LEVIE MAXXI',
    actorName: 'Anthony Weston Jr.',
    group: 'law-enforcement',
    order: 6,
    imageUrl: buildImageUrl('cast', 'levie-maxxi', 'cast'),
  },
  {
    id: 'detective-cage',
    characterName: 'NYPD DETECTIVE CAGE',
    actorName: 'Leroy Blocker',
    group: 'law-enforcement',
    order: 7,
    imageUrl: buildImageUrl('cast', 'detective-cage', 'cast'),
  },
  {
    id: 'detective-branson',
    characterName: 'DETECTIVE MARK BRANSON',
    actorName: 'Alonzo Ward',
    group: 'law-enforcement',
    order: 8,
    imageUrl: buildImageUrl('cast', 'detective-branson', 'cast'),
  },
  {
    id: 'detective-jefferies',
    characterName: 'DETECTIVE JEFFERIES',
    actorName: 'Ginette Jean',
    group: 'law-enforcement',
    order: 9,
    imageUrl: buildImageUrl('cast', 'detective-jefferies', 'cast'),
  },
  {
    id: 'detective-cordell',
    characterName: 'DETECTIVE CORDELL',
    actorName: 'Sid Savage',
    group: 'law-enforcement',
    order: 10,
    imageUrl: buildImageUrl('cast', 'detective-cordell', 'cast'),
  },
  {
    id: 'da-laurent',
    characterName: 'BRONX D.A. LAURENT',
    actorName: 'Tracey Harris',
    group: 'law-enforcement',
    order: 11,
    imageUrl: buildImageUrl('cast', 'da-laurent', 'cast'),
  },
  {
    id: 'da-crocket',
    characterName: 'BRONX D.A. CROCKET',
    actorName: 'Tahira Robinson',
    group: 'law-enforcement',
    order: 12,
    imageUrl: buildImageUrl('cast', 'da-crocket', 'cast'),
  },
  {
    id: 'ada-dorsey',
    characterName: 'A.D.A. DORSEY',
    actorName: 'DeMarcus Lassiter',
    group: 'law-enforcement',
    order: 13,
    imageUrl: buildImageUrl('cast', 'tony-cast-29', 'cast'),
  },
  {
    id: 'investigator-falco',
    characterName: 'INVESTIGATOR FALCO',
    actorName: 'Bunny Antoinette',
    group: 'law-enforcement',
    order: 14,
    imageUrl: buildImageUrl('cast', 'tony-cast-30', 'cast'),
  },
  {
    id: 'usda-morgan',
    characterName: 'USDA MORGAN',
    actorName: 'Donna Tucker-Jones',
    group: 'law-enforcement',
    order: 15,
  },
  {
    id: 'ausda-wright',
    characterName: 'AUSDA ALEISHA WRIGHT',
    actorName: 'Rosa Fox',
    group: 'law-enforcement',
    order: 16,
  },
  {
    id: 'ausda-cannon',
    characterName: 'AUSDA CANNON',
    actorName: 'T Ski Valley',
    group: 'law-enforcement',
    order: 17,
  },
  {
    id: 'ausda-franklin',
    characterName: 'AUSDA FRANKLIN',
    actorName: 'Toni Warden',
    group: 'law-enforcement',
    order: 18,
  },
  {
    id: 'parole-warren',
    characterName: 'PAROLE OFFICER WARREN',
    actorName: 'Sheryl Ivey',
    group: 'law-enforcement',
    order: 19,
  },

  // === STREET & SUPPORTING ===
  {
    id: 'melonie-streetz',
    characterName: 'MELONIE ST. JEAN (STREETZ)',
    alias: 'STREETZ',
    actorName: 'Yogi Garland',
    group: 'street',
    order: 1,
    imageUrl: buildImageUrl('cast', 'melonie-streetz', 'cast'),
  },
  {
    id: 'marvin-bishop',
    characterName: 'MARVIN BISHOP SMITH',
    actorName: 'Craig De Lano Cobb',
    group: 'street',
    order: 2,
    imageUrl: buildImageUrl('cast', 'marvin-bishop', 'cast'),
  },
  {
    id: 'kat-calloway',
    characterName: 'KAT CALLOWAY',
    actorName: 'ElMeleek Ekko Seven',
    group: 'street',
    order: 3,
    imageUrl: buildImageUrl('cast', 'kat-calloway', 'cast'),
  },
  {
    id: 'shaborn',
    characterName: 'SHABORN',
    actorName: 'Tone Murk',
    group: 'street',
    order: 4,
    imageUrl: buildImageUrl('cast', 'shaborn', 'cast'),
  },
  {
    id: 'stixx',
    characterName: 'STIXX / MONICA ST. JOHN',
    alias: 'STIXX',
    actorName: 'Tasha Woodard',
    group: 'street',
    order: 5,
  },
  {
    id: 'joyce-jasper',
    characterName: 'JOYCE JASPER',
    actorName: 'Annzada Hickson',
    group: 'street',
    order: 6,
  },
  {
    id: 'jamaican-kash',
    characterName: 'JAMAICAN KASH',
    actorName: 'Chad Royale',
    group: 'street',
    order: 7,
  },
  {
    id: 'jules',
    characterName: 'JULES',
    actorName: 'April Lee',
    group: 'street',
    order: 8,
  },
  {
    id: 'ashley-gemini',
    characterName: 'ASHLEY LeCROIX (GEMINI)',
    alias: 'GEMINI',
    actorName: 'Lisha Perkins',
    group: 'street',
    order: 9,
  },
  {
    id: 'cairo-lecroix',
    characterName: 'CAIRO LeCROIX',
    actorName: 'Bella Rae Bond',
    group: 'street',
    order: 10,
  },
  {
    id: 'big-connie',
    characterName: 'BIG CONNIE',
    actorName: 'Ruchelle Taylor',
    group: 'street',
    order: 11,
  },
  {
    id: 'wally-boy',
    characterName: 'WALLY BOY',
    actorName: 'Antonio Sheppard',
    group: 'street',
    order: 12,
  },
  {
    id: 'staxx',
    characterName: 'STAXX',
    actorName: 'Shawnba Jones',
    group: 'street',
    order: 13,
  },
  {
    id: 'cross',
    characterName: 'CROSS',
    actorName: 'Julius Dorsey',
    group: 'street',
    order: 14,
  },
  {
    id: 'born',
    characterName: 'BORN',
    actorName: 'Julian Dorsey',
    group: 'street',
    order: 15,
    bio: 'The muscle and the strategist. Born moves in silence but his impact is loud. Loyalty is his currency, but inflation is hitting the streets.',
  },
  {
    id: 'gyptian',
    characterName: 'GYPTIAN',
    actorName: 'Daniel Charles DesVerges',
    group: 'street',
    order: 16,
  },
  {
    id: 'sheran-griffin',
    characterName: 'SHERAN GRIFFIN',
    actorName: 'Money Pot',
    group: 'street',
    order: 17,
  },
  {
    id: 'jennifer-askew',
    characterName: 'DIAMOND',
    alias: 'DIAMOND',
    actorName: 'Jennifer Askew',
    group: 'street',
    order: 18,
    bio: 'Caught in the crossfire of the Bronx streets, Diamond shines bright amidst the chaos, navigating the gritty underworld with razor-sharp ambition.',
    imageUrl: buildImageUrl('cast', 'jennifer-askew', 'cast'),
    traits: ['Ambitious', 'Fearless', 'Loyal'],
  },

  // === COMMUNITY & FAITH ===
  {
    id: 'pastor-kellie',
    characterName: 'PASTOR KELLIE',
    actorName: 'Sharon White-Harrigan',
    group: 'community',
    order: 1,
  },
  {
    id: 'faith-edwards',
    characterName: 'FAITH EDWARDS',
    actorName: 'Tia Santiago',
    group: 'community',
    order: 2,
  },
  {
    id: 'imani-jefferies',
    characterName: 'IMANI JEFFERIES',
    actorName: 'Nae Watson',
    group: 'community',
    order: 3,
  },
  {
    id: 'tika',
    characterName: 'TIKA',
    actorName: "A'eLLE Fredrick",
    group: 'community',
    order: 4,
  },
  {
    id: 'cory-wright',
    characterName: 'CORY WRIGHT',
    actorName: 'Arnold Wilson',
    group: 'community',
    order: 5,
  },
  {
    id: 'lola-francis',
    characterName: 'LOLA FRANCIS',
    actorName: 'Tiara Nicole LEE',
    group: 'community',
    order: 6,
  },
  {
    id: 'melissa-crane',
    characterName: 'MELISSA CRANE',
    actorName: 'Sharita Moore-Willis',
    group: 'community',
    order: 7,
  },
  {
    id: 'nicole',
    characterName: 'NICOLE',
    actorName: 'Shayla Moore',
    group: 'community',
    order: 8,
  },
  {
    id: 'damani-morgan',
    characterName: 'DAMANI MORGAN',
    actorName: 'Kamari Lewis',
    group: 'community',
    order: 9,
  },

  // === SUPPORTING CAST (STUDIO PORTRAITS) ===
  ...Array.from({ length: 28 }, (_, i) => ({
    id: `supporting-cast-${i + 1}`,
    characterName: `SUPPORTING CAST ${i + 1}`,
    actorName: 'T.O.N.Y. Ensemble',
    group: 'street' as const,
    order: 100 + i,
    imageUrl: buildImageUrl('cast', `tony-cast-${String(i + 1).padStart(2, '0')}`, 'cast'),
  })),
];
