import { CastMember, Episode, NavLink, NewsItem, PressAsset, PressContact, QuickFact, EnhancedCastMember, CastGroupInfo } from './types';
import { buildImageUrl } from './lib/media';

export const NAV_LINKS: NavLink[] = [
  { label: 'Overview', href: '#overview' },
  { label: 'Cast', href: '#cast' },
  { label: 'Episodes', href: '#episodes' },
  { label: 'News', href: '#news' },
  // Press Kit hidden until assets are ready - restore by setting VITE_ENABLE_PRESS_KIT=true
  // { label: 'Press Kit', href: '#presskit' },
  { label: 'Contact', href: '#contact' },
];

export const CAST_MEMBERS: CastMember[] = [
  {
    id: '1',
    name: 'Michael Steven-Paul',
    role: "Michael 'El Bastardo' Cortez",
    bio: 'The creator and lead of the series. Michael Cortez is a key player in the Bronx streets, navigating the treacherous collision between the Cortez family legacy and the Beaumont empire while protecting his own from the demons of his past.',
    imageUrl: buildImageUrl('cast', 'michael-steven-paul', 'cast'),
  },
  {
    id: '2',
    name: 'Michelle White',
    role: "Phoenix 'Miss B' Beaumont",
    bio: 'The Queen Pin of the Beaumont empire. Phoenix commands respect and fear in equal measure, running her organization with an iron will and a strategic mind that keeps everyone guessing.',
    imageUrl: buildImageUrl('cast', 'michelle-white', 'cast'),
  },
  {
    id: '3',
    name: 'Britton L. Carter',
    role: 'Billy Black',
    bio: 'The Street King with a history that runs deep with Michael. Billy Black moves with calculated precision, and his next play could shift the balance of power across the entire Bronx.',
    imageUrl: buildImageUrl('cast', 'britton-carter', 'cast'),
  },
  {
    id: '4',
    name: 'Julian Dorsey',
    role: 'Born',
    bio: 'The muscle and the strategist. Born moves in silence but his impact is loud. Loyalty is his currency, but inflation is hitting the streets.',
    imageUrl: buildImageUrl('cast', 'julian-dorsey', 'cast'),
  },
  {
    id: '5',
    name: 'Shana Bookman',
    role: 'Rina',
    bio: 'Caught in the crossfire between families, Rina holds secrets that could reshape alliances or destroy them. Her survival depends on who she trusts—and who trusts her.',
    imageUrl: buildImageUrl('cast', 'shana-bookman', 'cast'),
  },
  {
    id: '6',
    name: 'Raymond Broadwater',
    role: 'Enrique Cortez',
    bio: 'The patriarch of the Cortez family. Enrique\'s legacy looms large over Michael, and the weight of family expectation is as heavy as any threat from the streets.',
    imageUrl: buildImageUrl('cast', 'raymond-broadwater', 'cast'),
  },
];

export const EPISODES: Episode[] = [
  {
    id: 's1e1',
    number: 1,
    title: 'Concrete Jungle',
    slug: 's1e1-concrete-jungle',
    isFree: false, // Paid - full season purchase required
    status: 'available', // Episode 1 is available now
    description: 'Michael Cortez returns to the Bronx after years away, only to find the streets he once knew have new kings—and old debts waiting to be collected.',
    airDate: 'Oct 12, 2023',
    duration: '48m',
    thumbnailUrl: buildImageUrl('episodes', 's01e01-concrete-jungle', 'card'),
  },
  {
    id: 's1e2',
    number: 2,
    title: 'Shadows of the Empire',
    slug: 's1e2-shadows-of-the-empire',
    isFree: false,
    status: 'in-production', // In production
    releaseDate: 'Spring 2026', // Expected release
    description: 'Billy Black makes his move for territory while Miss B summons Michael to discuss the future of the Beaumont empire. Trust is a luxury no one can afford.',
    airDate: 'TBA',
    duration: '52m',
    thumbnailUrl: buildImageUrl('episodes', 's01e02-shadows-of-the-empire', 'card'),
  },
  {
    id: 's1e3',
    number: 3,
    title: 'Bridge and Tunnel',
    slug: 's1e3-bridge-and-tunnel',
    isFree: false,
    status: 'in-production', // In production
    releaseDate: 'Spring 2026', // Expected release
    description: 'As law enforcement closes in, alliances are tested. Michael must choose between protecting the Cortez family legacy and his own survival.',
    airDate: 'TBA',
    duration: '50m',
    thumbnailUrl: buildImageUrl('episodes', 's01e03-bridge-and-tunnel', 'card'),
  },
];

export const NEWS_ITEMS: NewsItem[] = [
  {
    id: 'n1',
    title: 'Season 2 Renewed!',
    summary: 'T.O.N.Y. will return for a second season. Filming begins in Brooklyn this Spring.',
    date: 'Dec 15, 2023',
    category: 'Production',
    imageUrl: buildImageUrl('press', 'season-2-renewed', 'card'),
  },
  {
    id: 'n2',
    title: 'Red Carpet Premiere',
    summary: 'See the photos from the star-studded event at the Tribeca Film Festival.',
    date: 'Nov 02, 2023',
    category: 'Event',
    imageUrl: buildImageUrl('press', 'red-carpet-premiere', 'card'),
  },
];

export const SOCIAL_LINKS = {
  youtube: 'https://www.youtube.com/@TONYSeries',
  tiktok: 'https://www.tiktok.com/@tonyseries',
  instagram: 'https://www.instagram.com/tonyseries/',
  twitter: 'https://twitter.com/tonyseries',
  facebook: 'https://www.facebook.com/tonyseries',
  discord: 'https://discord.gg/tonyseries',
};

// Press Kit Data
export const QUICK_FACTS: QuickFact[] = [
  { label: 'Genre', value: 'Crime Drama' },
  { label: 'Creator', value: 'Michael Steven-Paul' },
  { label: 'Episodes', value: '10 per season' },
  { label: 'Runtime', value: '48-52 min' },
  { label: 'Network', value: 'Streaming' },
  { label: 'Premiere', value: 'Oct 2023' },
];

export const PRESS_CONTACTS: PressContact[] = [
  { name: 'Press Inquiries', role: 'Media Relations', email: 'press@tonyseries.com' },
  { name: 'Partnerships', role: 'Business Development', email: 'partners@tonyseries.com' },
];

export const PRESS_ASSETS: PressAsset[] = [
  // Photos
  {
    id: 'cast-headshots',
    title: 'Cast Headshots Pack',
    category: 'photo',
    description: 'High-resolution headshots of all main cast members',
    thumbnailUrl: buildImageUrl('press', 'cast-headshots-thumb', 'card'),
    downloadUrl: '/assets/press/TONY_cast_headshots.zip',
    fileSize: '45 MB',
    format: 'ZIP (JPEG)',
    resolution: '3000x4500 @ 300dpi',
  },
  {
    id: 'key-art',
    title: 'Key Art & Posters',
    category: 'photo',
    description: 'Official poster artwork and key promotional images',
    thumbnailUrl: buildImageUrl('press', 'key-art-thumb', 'card'),
    downloadUrl: '/assets/press/TONY_key_art.zip',
    fileSize: '32 MB',
    format: 'ZIP (PNG/JPEG)',
    resolution: '4000x6000 @ 300dpi',
  },
  {
    id: 'bts-gallery',
    title: 'Behind-the-Scenes Gallery',
    category: 'photo',
    description: 'Exclusive on-set photos from production',
    thumbnailUrl: buildImageUrl('press', 'bts-gallery-thumb', 'card'),
    downloadUrl: '/assets/press/TONY_bts_gallery.zip',
    fileSize: '78 MB',
    format: 'ZIP (JPEG)',
    resolution: '4000x2667 @ 300dpi',
  },
  {
    id: 'episode-stills',
    title: 'Episode Stills',
    category: 'photo',
    description: 'Selected high-quality stills from Season 1 episodes',
    thumbnailUrl: buildImageUrl('press', 'episode-stills-thumb', 'card'),
    downloadUrl: '/assets/press/TONY_episode_stills.zip',
    fileSize: '56 MB',
    format: 'ZIP (JPEG)',
    resolution: '3840x2160',
  },
  // Videos
  {
    id: 'official-trailer',
    title: 'Official Trailer',
    category: 'video',
    description: 'Season 1 official theatrical trailer',
    thumbnailUrl: buildImageUrl('press', 'trailer-thumb', 'card'),
    downloadUrl: '/assets/press/TONY_S01_trailer_1080p.mp4',
    fileSize: '125 MB',
    format: 'MP4 (H.264)',
    resolution: '1920x1080',
    duration: '2:15',
  },
  {
    id: 'teaser',
    title: 'Season Teaser',
    category: 'video',
    description: '30-second teaser for social media and broadcast',
    thumbnailUrl: buildImageUrl('press', 'teaser-thumb', 'card'),
    downloadUrl: '/assets/press/TONY_S01_teaser_1080p.mp4',
    fileSize: '28 MB',
    format: 'MP4 (H.264)',
    resolution: '1920x1080',
    duration: '0:30',
  },
  {
    id: 'bts-featurette',
    title: 'Making of T.O.N.Y.',
    category: 'video',
    description: 'Behind-the-scenes featurette with cast and crew interviews',
    thumbnailUrl: buildImageUrl('press', 'bts-featurette-thumb', 'card'),
    downloadUrl: '/assets/press/TONY_making_of_1080p.mp4',
    fileSize: '340 MB',
    format: 'MP4 (H.264)',
    resolution: '1920x1080',
    duration: '8:45',
  },
  // Logos
  {
    id: 'logo-primary',
    title: 'Primary Logo Pack',
    category: 'logo',
    description: 'Full logo in various formats (SVG, PNG, EPS)',
    thumbnailUrl: buildImageUrl('press', 'logo-primary-thumb', 'card'),
    downloadUrl: '/assets/press/TONY_logo_primary.zip',
    fileSize: '2.5 MB',
    format: 'ZIP (SVG/PNG/EPS)',
  },
  {
    id: 'logo-variations',
    title: 'Logo Variations',
    category: 'logo',
    description: 'Horizontal, vertical, and icon-only variations',
    thumbnailUrl: buildImageUrl('press', 'logo-variations-thumb', 'card'),
    downloadUrl: '/assets/press/TONY_logo_variations.zip',
    fileSize: '4.2 MB',
    format: 'ZIP (SVG/PNG)',
  },
  // Documents
  {
    id: 'press-release',
    title: 'Press Release',
    category: 'document',
    description: 'Official press release for Season 1 premiere',
    thumbnailUrl: buildImageUrl('press', 'press-release-thumb', 'card'),
    downloadUrl: '/assets/press/TONY_press_release.pdf',
    fileSize: '245 KB',
    format: 'PDF',
  },
  {
    id: 'fact-sheet',
    title: 'Series Fact Sheet',
    category: 'document',
    description: 'One-page overview with key facts and figures',
    thumbnailUrl: buildImageUrl('press', 'fact-sheet-thumb', 'card'),
    downloadUrl: '/assets/press/TONY_fact_sheet.pdf',
    fileSize: '180 KB',
    format: 'PDF',
  },
  {
    id: 'episode-guide',
    title: 'Episode Guide',
    category: 'document',
    description: 'Season 1 episode synopses and air dates',
    thumbnailUrl: buildImageUrl('press', 'episode-guide-thumb', 'card'),
    downloadUrl: '/assets/press/TONY_episode_guide.pdf',
    fileSize: '520 KB',
    format: 'PDF',
  },
  {
    id: 'cast-bios',
    title: 'Cast Bios',
    category: 'document',
    description: 'Detailed biographies of all main cast members',
    thumbnailUrl: buildImageUrl('press', 'cast-bios-thumb', 'card'),
    downloadUrl: '/assets/press/TONY_cast_bios.pdf',
    fileSize: '1.2 MB',
    format: 'PDF',
  },
];

// Enhanced Cast System
export const CAST_GROUPS: CastGroupInfo[] = [
  { id: 'main', label: 'Main Cast' },
  { id: 'beaumont-family', label: 'The Beaumont Family' },
  { id: 'cortez-family', label: 'The Cortez Family' },
  { id: 'law-enforcement', label: 'Law Enforcement & Legal' },
  { id: 'street', label: 'Street & Supporting' },
  { id: 'community', label: 'Community & Faith' },
];

export const ENHANCED_CAST: EnhancedCastMember[] = [
  // === MAIN CAST ===
  {
    id: 'michael-cortez',
    characterName: 'MICHAEL "El Bastardo" CORTEZ',
    alias: 'El Bastardo',
    actorName: 'Michael Steven-Paul',
    group: 'main',
    order: 1,
    isFeatured: true,
    bio: 'The creator and lead of the series. Michael Cortez navigates the corrupt underbelly of NYC while trying to keep his family safe from the demons of his past.',
    imageUrl: buildImageUrl('cast', 'michael-steven-paul', 'cast'),
    traits: ['Mastermind', 'Ruthless', 'Family Man'],
  },
  {
    id: 'pheonix-beaumont',
    characterName: 'PHEONIX BEAUMONT (Miss B)',
    alias: 'Miss B',
    actorName: 'Michelle White',
    group: 'main',
    order: 2,
    isFeatured: true,
    imageUrl: buildImageUrl('cast', 'michelle-white', 'cast'),
    traits: ['Queen Pin', 'Strategic', 'Fearless'],
    bio: 'The matriarch of the Beaumont empire. Miss B runs her operations with an iron fist and a velvet glove.',
  },
  {
    id: 'rina',
    characterName: 'RINA',
    actorName: 'Shana Bookman',
    group: 'main',
    order: 3,
    isFeatured: true,
    bio: 'Caught in the crossfire between families, Rina holds secrets that could reshape alliances or destroy them. Her survival depends on who she trusts—and who trusts her.',
    imageUrl: buildImageUrl('cast', 'shana-bookman', 'cast'),
    traits: ['Survivor', 'Secret Keeper', 'Unpredictable'],
  },
  {
    id: 'billy-black',
    characterName: 'BILLY BLACK',
    actorName: 'Britton Carter',
    group: 'main',
    order: 4,
    isFeatured: true,
    bio: 'A complex antagonist who rules the streets with a code of honor. His rivalry with Michael is personal, deep-rooted in their shared history in the Bronx.',
    imageUrl: buildImageUrl('cast', 'britton-carter', 'cast'),
    traits: ['Street King', 'Loyal', 'Dangerous'],
  },
  {
    id: 'enrique-cortez',
    characterName: 'ENRIQUE CORTEZ',
    actorName: 'Raymond Broadwater',
    group: 'main',
    order: 5,
    isFeatured: true,
    imageUrl: buildImageUrl('cast', 'raymond-broadwater', 'cast'),
    traits: ['Patriarch', 'Old School', 'Respected'],
    bio: 'The head of the Cortez family. His word is law, and his legacy is built on decades of power.',
  },
  {
    id: 'marisol-cortez',
    characterName: 'MARISOL CORTEZ',
    actorName: 'Lynell Payano',
    group: 'main',
    order: 6,
    isFeatured: true,
    imageUrl: buildImageUrl('cast', 'lynell-payano', 'cast'),
    traits: ['Matriarch', 'Protector', 'Fierce'],
    bio: 'The heart of the Cortez family. She holds them together through every storm.',
  },
  {
    id: 'selina-cortez',
    characterName: 'SELINA CORTEZ',
    actorName: 'Leslie Pena',
    group: 'main',
    order: 7,
    isFeatured: true,
    imageUrl: buildImageUrl('cast', 'leslie-pena', 'cast'),
    traits: ['Ambitious', 'Cunning', 'Rising Star'],
    bio: 'The youngest Cortez with the most to prove. She\'s ready to carve her own path.',
  },

  // === THE BEAUMONT FAMILY ===
  {
    id: 'jenesis-beaumont',
    characterName: 'JENESIS BEAUMONT',
    actorName: 'Tatiana Honesty',
    group: 'beaumont-family',
    order: 1,
  },
  {
    id: 'brandi-beaumont',
    characterName: 'BRANDI BEAUMONT',
    actorName: 'Bilae Harding',
    group: 'beaumont-family',
    order: 2,
  },
  {
    id: 'maxx-beaumont',
    characterName: 'MAXX BEAUMONT',
    actorName: 'Dwight Williams',
    group: 'beaumont-family',
    order: 3,
  },

  // === THE CORTEZ FAMILY ===
  {
    id: 'chelsea-alvarez',
    characterName: 'CHELSEA ALVAREZ',
    actorName: 'Kimani Sanders',
    group: 'cortez-family',
    order: 1,
  },
  {
    id: 'ricardo-alvarez',
    characterName: 'RICARDO ALVAREZ "Big Chicken"',
    alias: 'Big Chicken',
    actorName: 'John Garcia',
    group: 'cortez-family',
    order: 2,
  },
  {
    id: 'domingo',
    characterName: 'DOMINGO (Sonny)',
    alias: 'Sonny',
    actorName: 'Giodarni Vargas',
    group: 'cortez-family',
    order: 3,
  },

  // === LAW ENFORCEMENT & LEGAL ===
  {
    id: 'captain-reigns',
    characterName: 'NYPD CAPTAIN REIGNS',
    actorName: 'Liana Battise',
    group: 'law-enforcement',
    order: 1,
  },
  {
    id: 'detective-chase',
    characterName: 'NYPD DETECTIVE CHASE',
    actorName: 'Gilly Delgado',
    group: 'law-enforcement',
    order: 2,
  },
  {
    id: 'detective-barnes',
    characterName: 'NYPD DETECTIVE BARNES',
    actorName: 'Lezette Newland',
    group: 'law-enforcement',
    order: 3,
  },
  {
    id: 'detective-waters',
    characterName: 'NYPD DETECTIVE WATERS',
    actorName: 'Corrina Lynch',
    group: 'law-enforcement',
    order: 4,
  },
  {
    id: 'detective-kazaan',
    characterName: 'NYPD DETECTIVE KAZAAN',
    actorName: 'Fallon Shaya',
    group: 'law-enforcement',
    order: 5,
  },
  {
    id: 'levie-maxxi',
    characterName: 'NYPD LEVIE MAXXI',
    actorName: 'Anthony Weston Jr.',
    group: 'law-enforcement',
    order: 6,
  },
  {
    id: 'detective-cage',
    characterName: 'NYPD DETECTIVE CAGE',
    actorName: 'Leroy Blocker',
    group: 'law-enforcement',
    order: 7,
  },
  {
    id: 'detective-branson',
    characterName: 'DETECTIVE MARK BRANSON',
    actorName: 'Alonzo Ward',
    group: 'law-enforcement',
    order: 8,
  },
  {
    id: 'detective-jefferies',
    characterName: 'DETECTIVE JEFFERIES',
    actorName: 'Ginette Jean',
    group: 'law-enforcement',
    order: 9,
  },
  {
    id: 'detective-cordell',
    characterName: 'DETECTIVE CORDELL',
    actorName: 'Sid Savage',
    group: 'law-enforcement',
    order: 10,
  },
  {
    id: 'da-laurent',
    characterName: 'BRONX D.A. LAURENT',
    actorName: 'Tracey Harris',
    group: 'law-enforcement',
    order: 11,
  },
  {
    id: 'da-crocket',
    characterName: 'BRONX D.A. CROCKET',
    actorName: 'Tahira Robinson',
    group: 'law-enforcement',
    order: 12,
  },
  {
    id: 'ada-dorsey',
    characterName: 'A.D.A. DORSEY',
    actorName: 'DeMarcus Lassiter',
    group: 'law-enforcement',
    order: 13,
  },
  {
    id: 'investigator-falco',
    characterName: 'INVESTIGATOR FALCO',
    actorName: 'Bunny Antoinette',
    group: 'law-enforcement',
    order: 14,
  },
  {
    id: 'usda-morgan',
    characterName: 'USDA MORGAN',
    actorName: 'Donna Tucker-Jones',
    group: 'law-enforcement',
    order: 15,
  },
  {
    id: 'ausda-wright',
    characterName: 'AUSDA ALEISHA WRIGHT',
    actorName: 'Rosa Fox',
    group: 'law-enforcement',
    order: 16,
  },
  {
    id: 'ausda-cannon',
    characterName: 'AUSDA CANNON',
    actorName: 'T Ski Valley',
    group: 'law-enforcement',
    order: 17,
  },
  {
    id: 'ausda-franklin',
    characterName: 'AUSDA FRANKLIN',
    actorName: 'Toni Warden',
    group: 'law-enforcement',
    order: 18,
  },
  {
    id: 'parole-warren',
    characterName: 'PAROLE OFFICER WARREN',
    actorName: 'Sheryl Ivey',
    group: 'law-enforcement',
    order: 19,
  },

  // === STREET & SUPPORTING ===
  {
    id: 'melonie-streetz',
    characterName: 'MELONIE ST. JEAN (STREETZ)',
    alias: 'STREETZ',
    actorName: 'Yogi Garland',
    group: 'street',
    order: 1,
  },
  {
    id: 'marvin-bishop',
    characterName: 'MARVIN BISHOP SMITH',
    actorName: 'Craig De Lano Cobb',
    group: 'street',
    order: 2,
  },
  {
    id: 'kat-calloway',
    characterName: 'KAT CALLOWAY',
    actorName: 'ElMeleek Ekko Seven',
    group: 'street',
    order: 3,
  },
  {
    id: 'shaborn',
    characterName: 'SHABORN',
    actorName: 'Tone Murk',
    group: 'street',
    order: 4,
  },
  {
    id: 'stixx',
    characterName: 'STIXX / MONICA ST. JOHN',
    alias: 'STIXX',
    actorName: 'Tasha Woodard',
    group: 'street',
    order: 5,
  },
  {
    id: 'joyce-jasper',
    characterName: 'JOYCE JASPER',
    actorName: 'Annzada Hickson',
    group: 'street',
    order: 6,
  },
  {
    id: 'jamaican-kash',
    characterName: 'JAMAICAN KASH',
    actorName: 'Chad Royale',
    group: 'street',
    order: 7,
  },
  {
    id: 'jules',
    characterName: 'JULES',
    actorName: 'April Lee',
    group: 'street',
    order: 8,
  },
  {
    id: 'ashley-gemini',
    characterName: 'ASHLEY LeCROIX (GEMINI)',
    alias: 'GEMINI',
    actorName: 'Lisha Perkins',
    group: 'street',
    order: 9,
  },
  {
    id: 'cairo-lecroix',
    characterName: 'CAIRO LeCROIX',
    actorName: 'Bella Rae Bond',
    group: 'street',
    order: 10,
  },
  {
    id: 'big-connie',
    characterName: 'BIG CONNIE',
    actorName: 'Ruchelle Taylor',
    group: 'street',
    order: 11,
  },
  {
    id: 'wally-boy',
    characterName: 'WALLY BOY',
    actorName: 'Antonio Sheppard',
    group: 'street',
    order: 12,
  },
  {
    id: 'staxx',
    characterName: 'STAXX',
    actorName: 'Shawnba Jones',
    group: 'street',
    order: 13,
  },
  {
    id: 'cross',
    characterName: 'CROSS',
    actorName: 'Julius Dorsey',
    group: 'street',
    order: 14,
  },
  {
    id: 'born',
    characterName: 'BORN',
    actorName: 'Julian Dorsey',
    group: 'street',
    order: 15,
    bio: 'The muscle and the strategist. Born moves in silence but his impact is loud. Loyalty is his currency, but inflation is hitting the streets.',
  },
  {
    id: 'gyptian',
    characterName: 'GYPTIAN',
    actorName: 'Daniel Charles DesVerges',
    group: 'street',
    order: 16,
  },
  {
    id: 'sheran-griffin',
    characterName: 'SHERAN GRIFFIN',
    actorName: 'Money Pot',
    group: 'street',
    order: 17,
  },

  // === COMMUNITY & FAITH ===
  {
    id: 'pastor-kellie',
    characterName: 'PASTOR KELLIE',
    actorName: 'Sharon White-Harrigan',
    group: 'community',
    order: 1,
  },
  {
    id: 'faith-edwards',
    characterName: 'FAITH EDWARDS',
    actorName: 'Tia Santiago',
    group: 'community',
    order: 2,
  },
  {
    id: 'imani-jefferies',
    characterName: 'IMANI JEFFERIES',
    actorName: 'Nae Watson',
    group: 'community',
    order: 3,
  },
  {
    id: 'tika',
    characterName: 'TIKA',
    actorName: "A'eLLE Fredrick",
    group: 'community',
    order: 4,
  },
  {
    id: 'cory-wright',
    characterName: 'CORY WRIGHT',
    actorName: 'Arnold Wilson',
    group: 'community',
    order: 5,
  },
  {
    id: 'lola-francis',
    characterName: 'LOLA FRANCIS',
    actorName: 'Tiara Nicole LEE',
    group: 'community',
    order: 6,
  },
  {
    id: 'melissa-crane',
    characterName: 'MELISSA CRANE',
    actorName: 'Sharita Moore-Willis',
    group: 'community',
    order: 7,
  },
  {
    id: 'nicole',
    characterName: 'NICOLE',
    actorName: 'Shayla Moore',
    group: 'community',
    order: 8,
  },
  {
    id: 'damani-morgan',
    characterName: 'DAMANI MORGAN',
    actorName: 'Kamari Lewis',
    group: 'community',
    order: 9,
  },
];
